const UPDATE_ACCOUNT_DATA = "UPDATE_ACCOUNT_DATA";
const UPDATE_EMAIL_AVAILABLE = "UPDATE_EMAIL_AVAILABLE";
const UPDATE_AUTH_KEY = "UPDATE_AUTH_KEY";

export { UPDATE_ACCOUNT_DATA, UPDATE_EMAIL_AVAILABLE, UPDATE_AUTH_KEY };
