const UPDATE_ACCOUNT_DATA = "UPDATE_ACCOUNT_DATA";
const UPDATE_EMAIL_AVAILABLE = "UPDATE_EMAIL_AVAILABLE";
const UPDATE_AUTH_KEY = "UPDATE_AUTH_KEY";
const UPDATE_INDEX_REPORT = "UPDATE_INDEX_REPORT";
const KILL_INDEX_REPORT = "KILL_INDEX_REPORT";
const FILTER_UPDATE = "FILTER_UPDATE";

export {
  UPDATE_ACCOUNT_DATA,
  UPDATE_EMAIL_AVAILABLE,
  UPDATE_AUTH_KEY,
  UPDATE_INDEX_REPORT,
  KILL_INDEX_REPORT,
  FILTER_UPDATE,
};
