const index_report = [
  {
    id: null,
    applicant_id: 3,
    applicant_name: "Hannibal Luch",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u1.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 1,
    aplication_date: "2020-10-07T13:08:12.540Z",
    evaluation: 0,
    admin_id: 1,
    evaluator_name: "Carlos Anriquez",
  },
  {
    id: null,
    applicant_id: 4,
    applicant_name: "Clara Branch",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u2.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 2,
    aplication_date: "2020-10-07T13:08:12.545Z",
    evaluation: 1,
    admin_id: 1,
    evaluator_name: "Carlos Anriquez",
  },
  {
    id: null,
    applicant_id: 5,
    applicant_name: "Sylvia Commit",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u3.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 3,
    aplication_date: "2020-10-07T13:08:12.550Z",
    evaluation: 0,
    admin_id: 1,
    evaluator_name: "Carlos Anriquez",
  },
  {
    id: null,
    applicant_id: 6,
    applicant_name: "Carolyn Format",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u4.png",
    job_name: "Digital Marketing Intern",
    job_id: 2,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.520Z",
    application_id: 4,
    aplication_date: "2020-10-07T13:08:12.555Z",
    evaluation: 0,
    admin_id: 1,
    evaluator_name: "Carlos Anriquez",
  },
  {
    id: null,
    applicant_id: 7,
    applicant_name: "Pedro Syntax",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u5.png",
    job_name: "Human Resources Intern",
    job_id: 3,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.523Z",
    application_id: 5,
    aplication_date: "2020-10-07T13:08:12.560Z",
    evaluation: 0,
    admin_id: 1,
    evaluator_name: "Carlos Anriquez",
  },
  {
    id: null,
    applicant_id: 3,
    applicant_name: "Hannibal Luch",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u1.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 1,
    aplication_date: "2020-10-07T13:08:12.540Z",
    evaluation: 1,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 4,
    applicant_name: "Clara Branch",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u2.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 2,
    aplication_date: "2020-10-07T13:08:12.545Z",
    evaluation: 1,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 5,
    applicant_name: "Sylvia Commit",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u3.png",
    job_name: "Information Technology Intern",
    job_id: 1,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.516Z",
    application_id: 3,
    aplication_date: "2020-10-07T13:08:12.550Z",
    evaluation: 1,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 6,
    applicant_name: "Carolyn Format",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u4.png",
    job_name: "Digital Marketing Intern",
    job_id: 2,
    author_id: 1,
    jobpost_author: "Carlos Anriquez",
    jobpost_date: "2020-10-07T13:08:12.520Z",
    application_id: 4,
    aplication_date: "2020-10-07T13:08:12.555Z",
    evaluation: 0,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 7,
    applicant_name: "Pedro Syntax",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u5.png",
    job_name: "Human Resources Intern",
    job_id: 3,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.523Z",
    application_id: 5,
    aplication_date: "2020-10-07T13:08:12.560Z",
    evaluation: 0,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 8,
    applicant_name: "Jhonny Fastkeys",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u6.png",
    job_name: "Sales Intern",
    job_id: 4,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.526Z",
    application_id: 6,
    aplication_date: "2020-10-07T13:08:12.564Z",
    evaluation: 0,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 9,
    applicant_name: "Lissa Learner",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u8.png",
    job_name: "Sales Intern",
    job_id: 4,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.526Z",
    application_id: 7,
    aplication_date: "2020-10-07T13:08:12.571Z",
    evaluation: 0,
    admin_id: 2,
    evaluator_name: "Cecilia Fernandez",
  },
  {
    id: null,
    applicant_id: 8,
    applicant_name: "Jhonny Fastkeys",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u6.png",
    job_name: "Human Resources Intern",
    job_id: 3,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.523Z",
    application_id: 8,
    aplication_date: "2020-10-07T13:08:12.576Z",
    evaluation: null,
    admin_id: null,
    evaluator_name: null,
  },
  {
    id: null,
    applicant_id: 6,
    applicant_name: "Carolyn Format",
    applicant_avatar: "https://anri-img-storage.s3.amazonaws.com/avatar/u4.png",
    job_name: "Human Resources Intern",
    job_id: 3,
    author_id: 2,
    jobpost_author: "Cecilia Fernandez",
    jobpost_date: "2020-10-07T13:08:12.523Z",
    application_id: 9,
    aplication_date: "2020-10-07T13:08:12.580Z",
    evaluation: null,
    admin_id: null,
    evaluator_name: null,
  },
];

export default index_report;
